# Generated by Django 3.2 on 2021-07-15 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20210713_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
